name: neardb
description: NearDB is a simple database that leverages cloud infrastructure like document storage and CDN to deliver an inexpensive unbelievably scalable document database optimized for reads and perfect for edge applications.
version: 0.3.0-dev.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.0
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
